name: Deploy Subsocial Rust Docs to dappforce/rust-docs repository

on:
  workflow_dispatch:
  push:
    tags: [ 'v*' ]

jobs:
  deploy-docs:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set-Up
        run: sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl

      - name: Install Rustup
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source ~/.cargo/env
          ./scripts/init.sh

      - name: Build docs
        run: |
          SKIP_WASM_BUILD=1 ./scripts/generate-docs.sh

      - name: Prepare GitHub Pages repository
        run: |
          VERSION=$(grep -m 1 '^version' "$ROOT_DIR/runtime/Cargo.toml" | egrep -o '[0-9\.]+')
          mkdir pages
          mv target/doc pages/v$VERSION
          cp scripts/docs-static/* pages/
          ln -s v$VERSION pages/latest

      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: dappforce/rust-docs
          publish_dir: ./pages
          publish_branch: main
